version: "3.8"
services:
  portfolio:
    image: ghcr.io/yosefxk/portfolio:latest
    container_name: portfolio
    ports:
      - "4175:8080"
    restart: unless-stopped
    networks:
      - media_network

networks:
  media_network:
    external: true
